### ISSUE TITLE
Error with testthat 2.0.0: Can't mock functions in base packages (utils)

### ISSUE THREAD

**Issue by MarkEdmondson1234** [nealrichardson/httptest#10]
I just updated to `testthat` 2.0.0 candidate as I got a message it would break tests, and on rerun it states:

`error: (unknown)
Can't mock functions in base packages (utils)`

Which I guess is to do with `httptests` dependency on `testthat`and this breaking change:
https://github.com/r-lib/testthat/blob/master/NEWS.md#testthat-1029000

**Comment by nealrichardson** [comment]
Yes, thanks, I'm aware, and I have a release that addresses this that is stuck in CRAN purgatory. (https://github.com/nealrichardson/httptest/commit/570ffffa7332eb45b5618be749a5acfd85f3da0f alludes to the issue.) Hope to have this resolved ASAP, but in the meantime, the master branch on GitHub does work with testthat 2.0.0.
