### ISSUE TITLE
use_httptest() not exported in version 3.1.0 (CRAN's version)

### ISSUE THREAD

**Issue by ramiromagno** [nealrichardson/httptest#20]
hi,

It seems your guidelines on how to use this package are broken for CRAN's version 3.1.0 because the function `use_httptest()` is not exported.

Works fine though with version 3.1.1. (installed from github):

```R
# Previously installed from CRAN with install.packages("httptest")
library(httptest)
# Loading required package: testthat
```
```R
packageVersion("httptest")
# [1] ‘3.1.0’
```
```R
"use_httptest" %in% ls("package:httptest")
# [1] FALSE
```
```R
# Installing now the dev version from Github
detach("package:httptest", unload=TRUE)
devtools::install_github("nealrichardson/httptest")

# Downloading GitHub repo nealrichardson/httptest@master
# (...)
# * DONE (httptest)
```
```R
library(httptest)
packageVersion("httptest")
# [1] ‘3.1.1’
```
```R
"use_httptest" %in% ls("package:httptest")
# [1] TRUE
```

**Comment by nealrichardson** [comment]
Correct: the README.md in GitHub reflects what is in GitHub, which has not yet been released to CRAN. https://cran.r-project.org/web/packages/httptest/readme/README.html does not mention `use_httptest()`

We're due for a CRAN release, which will resolve this. Thanks for bringing it to my attention. In the meantime, README.md does explain what `use_httptest()` does, so you can add the package manually.

**Comment by ramiromagno** [comment]
Fair enough.

But if you keep upfront in your Github README.md:

```R
install.packages("httptest")
```

Then people are going to assume that whatever follows is applicable to your pkg regardless of where it's coming from.

**Comment by nealrichardson** [comment]
Yes, you are right, and thanks for pointing it out.
