### ISSUE TITLE
use_httptest() should create a file called setup not helper

### ISSUE THREAD

**Issue by maelle** [nealrichardson/httptest#44]
https://testthat.r-lib.org/reference/test_dir.html#special-files

**Comment by nealrichardson** [comment]
Apparently it should :) Revised the issue title accordingly.

**Comment by maelle** [comment]
Actually this might have been a bad idea? https://github.com/r-lib/testthat/issues/1206#issuecomment-713120193

**Comment by maelle** [comment]
I got confused, it was the right change https://testthat.r-lib.org/articles/test-fixtures.html#package
