### ISSUE TITLE
Could there be an FAQ index?

### ISSUE THREAD

**Issue by maelle** [nealrichardson/httptest#54]
At the moment the FAQ lives in the homepage so to get an overview of all questions one needs to scroll down.

Why not make the FAQ a [re-usable Rmd fragment](https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/) and have it both on the homepage and in a dedicated vignette? This way the FAQ vignette would have a TOC on the right.

**Comment by maelle** [comment]
I was thinking about it because webfakes' (formerly presser) how-to TOC is very handy. https://r-lib.github.io/webfakes/dev/articles/how-to.html

**Comment by nealrichardson** [comment]
I moved it to its own vignette, so you get the ToC sidebar in pkgdown. I agree that that's much nicer.
