### ISSUE TITLE
with_mock_api in combination with httr::upload_file seems to leak on win10

### ISSUE THREAD

**Issue by bitkid** [nealrichardson/httptest#60]
when i run my tests, i constantly see warnings like this:

Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 4 (./testdata/lfr/upload_test.md)

where upload_test.md is the file i use with httr::upload_file

by running tests i mean running devtools::test() in the same console multiple times

**Comment by nealrichardson** [comment]
Can you try with the dev version of the package? I think we've resolved this in the version we're planning to release at the end of the month. See https://github.com/nealrichardson/httptest/blob/master/NEWS.md.

**Comment by nealrichardson** [comment]
httptest 4.0.0 was released a month ago. Please reopen if you still see this issue with the latest release.
