### ISSUE TITLE
Plans for httr2 support?

### ISSUE THREAD

**Issue by maelle** [nealrichardson/httptest#65]
:wave: @nealrichardson! I was wondering if you had plans to support httr2. Thank you!

**Comment by nealrichardson** [comment]
I'd like to! Just haven't had the time to start on it. Would you be interested in helping?

**Comment by maelle** [comment]
I wouldn't have time in the short time either :grimacing: But thanks for suggesting :smile:

**Comment by nealrichardson** [comment]
I started https://github.com/nealrichardson/httptest2 and got much of it ported over to work on httr2. I put the rest of the (known) to-dos as Issues--hopefully they're more manageable in scope for folks (like you!) to be able to jump in.

**Comment by maelle** [comment]
Fantastic news, thank you!
