### ISSUE TITLE
When is proposed fix going to be released on CRAN?

### ISSUE THREAD

**Issue by dbarneche** [nealrichardson/httptest#82]
Hi, I am using this great fix which helps with mock tests--particularly, it allows the user to regenerate mock tests locally, and then save the new files with a shorter path structure via `set_requester`:
https://github.com/nealrichardson/httptest/commit/5fc2be9f8627fa36d04ee06de0291c1d7633d1a8
Thanks for this great package!

**Comment by nealrichardson** [comment]
Yeah we're overdue for a release. I'll try to submit next week.

**Comment by nealrichardson** [comment]
4.2.0 is on CRAN now: https://cran.r-project.org/web/packages/httptest/index.html

**Comment by dbarneche** [comment]
Thank you, much appreciated.
